name: "TIL"

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `main` branch containing content
        uses: actions/checkout@v3
        with:
          ref: main
          path: ./content/

      - name: Checkout `build` branch containing Hugo site
        uses: actions/checkout@v3
        with:
          ref: build
          path: ./build/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build the site with Hugo
        run: hugo -v --gc --debug --source ${GITHUB_WORKSPACE}/build/ --contentDir ${GITHUB_WORKSPACE}/content/ --destination ${GITHUB_WORKSPACE}/built

      - name: What is there?
        run: tree .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: published
          publish_dir: ./built

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
